name:                algrandhs
version:             0.1.0.0
github:              "mars0i/algrandhs"
license:             GPL-3
author:              "Marshall Abrams"
maintainer:          "marshall@logical.net"
copyright:           "2020 Marshall Abrams"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mars0i/algrandhs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  algrandhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algrandhs

tests:
  algrandhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - algrandhs
